name: Build & Package SfmcApp for macOS (.NET 9 DMG)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-15   # Xcode 16.4 required by .NET 9 MacCatalyst
    steps:
      - name: Show macOS version
        run: sw_vers

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Auto-increment version number (only on workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        id: versioning
        run: |
          FILE="SfmcApp/SfmcApp.csproj"
          CURRENT_VERSION=$(xmllint --xpath "string(//Project/PropertyGroup[Version]/Version)" "$FILE" 2>/dev/null)

          if [ -z "$CURRENT_VERSION" ]; then
            echo "No <Version> tag found. Adding default 1.0.0"
            sed -i '' '/<PropertyGroup>/a\
            \  <Version>1.0.0</Version>' "$FILE"
            CURRENT_VERSION="1.0.0"
          fi

          echo "Current version: $CURRENT_VERSION"

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          echo "New version: $NEW_VERSION"

          sed -i '' "s|<Version>$CURRENT_VERSION</Version>|<Version>$NEW_VERSION</Version>|" "$FILE"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit updated version (only on workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add SfmcApp/SfmcApp.csproj
          git commit -m "CI: Bump version to ${{ steps.versioning.outputs.version }} [skip ci]"
          git push

      - name: Restore dependencies
        run: dotnet restore SfmcApp/SfmcApp.csproj

      # Build arm64 .app bundle
      - name: Build arm64 .app
        run: |
          dotnet publish SfmcApp/SfmcApp.csproj \
            -c Release \
            -f net9.0-maccatalyst \
            -p:RuntimeIdentifier=maccatalyst-arm64 \
            -p:BuildAppBundle=true \
            -p:CreatePackage=false \
            -o publish/arm64
      
      - name: Build x64 .app
        run: |
          dotnet publish SfmcApp/SfmcApp.csproj \
            -c Release \
            -f net9.0-maccatalyst \
            -p:RuntimeIdentifier=maccatalyst-x64 \
            -p:BuildAppBundle=true \
            -p:CreatePackage=false \
            -o publish/x64
            
      - name: ls publish
        run: ls -R publish


      # Create DMG for arm64
      - name: Create arm64 DMG
        run: |
          VERSION=${{ steps.versioning.outputs.version || '0.0.0-CI' }}
          APP_PATH=$(find publish/arm64 -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: No .app bundle found in publish/arm64"
            ls -R publish/arm64
            exit 1
          fi
          mkdir -p output
          DMG_NAME="SfmcApp-macOS-arm64-${VERSION}.dmg"
          echo "Found app at $APP_PATH"
          hdiutil create -volname "SfmcApp Installer (arm64)" \
            -srcfolder "$APP_PATH" \
            -ov -format UDZO "output/$DMG_NAME"

      # Create DMG for x64
      - name: Create x64 DMG
        run: |
          VERSION=${{ steps.versioning.outputs.version || '0.0.0-CI' }}
          APP_PATH=$(find publish/x64 -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: No .app bundle found in publish/x64"
            ls -R publish/x64
            exit 1
          fi
          DMG_NAME="SfmcApp-macOS-x64-${VERSION}.dmg"
          echo "Found app at $APP_PATH"
          hdiutil create -volname "SfmcApp Installer (x64)" \
            -srcfolder "$APP_PATH" \
            -ov -format UDZO "output/$DMG_NAME"

      # Upload DMGs as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SfmcApp-DMGs
          path: output/*

      # Create GitHub Release with DMGs attached
      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
          tag_name: v${{ steps.versioning.outputs.version || '0.0.0-CI' }}
          name: "SfmcApp macOS v${{ steps.versioning.outputs.version || '0.0.0-CI' }}"
          draft: false
          prerelease: false
