name: Build & Package SfmcApp for macOS (.NET 9 DMG)

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-15   # Xcode 16.4 required by .NET 9 MacCatalyst
    steps:
      - name: Show macOS version
        run: sw_vers

      - name: Set up Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Versioning
        id: versioning
        run: |
          VERSION_FILE=VERSION.txt
          if [ ! -f $VERSION_FILE ]; then
            echo "0.1.0" > $VERSION_FILE
          fi
          OLD_VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r major minor patch <<< "$OLD_VERSION"
          NEW_VERSION="$major.$minor.$((patch+1))"
          echo "$NEW_VERSION" > $VERSION_FILE
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build arm64 app bundle
        run: |
          dotnet build SfmcApp/SfmcApp.csproj -c Release -f net9.0-maccatalyst -p:RuntimeIdentifier=maccatalyst-arm64
          mkdir -p output
          cp -R SfmcApp/bin/Release/net9.0-maccatalyst/maccatalyst-arm64/SfmcApp.app output/SfmcApp-arm64.app
          hdiutil create -volname SfmcApp -srcfolder output/SfmcApp-arm64.app -ov -format UDZO output/SfmcApp-macOS-arm64-${{ steps.versioning.outputs.version }}.dmg

      - name: Build x64 app bundle
        run: |
          dotnet build SfmcApp/SfmcApp.csproj -c Release -f net9.0-maccatalyst -p:RuntimeIdentifier=maccatalyst-x64
          mkdir -p output
          cp -R SfmcApp/bin/Release/net9.0-maccatalyst/maccatalyst-x64/SfmcApp.app output/SfmcApp-x64.app
          hdiutil create -volname SfmcApp -srcfolder output/SfmcApp-x64.app -ov -format UDZO output/SfmcApp-macOS-x64-${{ steps.versioning.outputs.version }}.dmg

      - name: Commit version bump
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add VERSION.txt
          git commit -m "Bump version to ${{ steps.versioning.outputs.version }}" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.versioning.outputs.version }}
          name: "Release ${{ steps.versioning.outputs.version }}"
          files: |
            output/SfmcApp-macOS-arm64-${{ steps.versioning.outputs.version }}.dmg
            output/SfmcApp-macOS-x64-${{ steps.versioning.outputs.version }}.dmg