name: Test Artifact

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dummy file
        run: echo "Hello world" > test.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: test.txt
